name: executorservices
description: A Dart package providing services that allow you to execute dart code in different executors, ex - isolates.
version: 1.0.2
homepage: https://github.com/bitsydarel/executorservices
author: darelbitsy <bitsydarel@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  meta: ^1.1.7

dev_dependencies:
  flutter_code_style: ^1.6.5
  test: ^1.9.1
  mockito: ^4.1.1
